apiVersion: v1
kind: Service
metadata:
  name: consensus-port-service
spec:
  # For local kubernetes you would need to install something like MetalLB on your cluster
  # AWS and other cloud providers handle this automatically with their load balancers
  type: LoadBalancer
  ports:
    - name: app
      port: 8080
      targetPort: 80
      protocol: TCP
  selector:
    app: consensus-port