name: Build and publish Docker image on release

on:
  release:
    types:
      - published

jobs:
  push_to_registry:
    name: Push Docker image to AWS ECR
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      # Docker Hub - For public repositories

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        env:
          DOCKER_ORGANIZATION: ${{ secrets.DOCKER_ORGANIZATION }}
          DOCKER_REPOSITORY: ${{ github.repository }}
          IMAGE_TAG: ${{ github.sha }}
          RELEASE_TAG: ${{ github.ref }}
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            $DOCKER_ORGANIZATION/$DOCKER_REPOSITORY:$IMAGE_TAG
            $DOCKER_ORGANIZATION/$DOCKER_REPOSITORY:$RELEASE_TAG
            $DOCKER_ORGANIZATION/$DOCKER_REPOSITORY:latest

      # AWS ECR - For private repositories
      #
      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.ECR_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.ECR_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ secrets.ECR_REGION }}

      # - name: Login to Amazon ECR
      #   id: login-ecr
      #   uses: aws-actions/amazon-ecr-login@v1

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1
      # - name: Build and push
      #   uses: docker/build-push-action@v2
      #   env:
      #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #     ECR_REPOSITORY: ${{ github.repository }}
      #     IMAGE_TAG: ${{ github.sha }}
      #     RELEASE_TAG: ${{ github.ref }}
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     push: true
      #     tags: |
      #       $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      #       $ECR_REGISTRY/$ECR_REPOSITORY:$RELEASE_TAG
      #       $ECR_REGISTRY/$ECR_REPOSITORY:latest
